{% set name = "zeus-mcmc" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 594baa90de4ad4488c4db5ed6a0446f7103bc4b3de787f4d7d23c91c9aa88769

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - pytest
    - python >={{ python_min }}
    - tqdm
    - scipy >=1.5.0
    - seaborn
    - scikit-learn

test:
  requires:
    - python {{ python_min }}
  imports:
    - zeus

about:
  home: https://zeus-mcmc.readthedocs.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'zeus: Lightning Fast MCMC'
  description: |
    zeus is a Python implementation of the Ensemble Slice Sampling method.

extra:
  recipe-maintainers:
    - minaskar
    - mattpitkin
